services:
  - type: web
    name: fave-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_CALLBACK_URL
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_FIRSTNAME
        sync: false
      - key: ADMIN_LASTNAME
        sync: false
  - type: web
    name: fave-frontend
    env: node
    buildCommand: cd frontend && npm install
    startCommand: cd frontend && npm start
    envVars:
      - key: PORT
        value: 3001